version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: voucher_core_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voucher_core
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
